name: CI Basic

on:
  push:
    branches: [ desarrollo ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: node ./node_modules/jest/bin/jest.js

      - name: Escaneo de dependencias
        run: npm audit || true

      - name: Escaneo SAST con Semgrep
        run: |
          python3 -m pip install semgrep
          semgrep --config auto . || true

      - name: Escaneo DAST con ZAP
        run: |
          npm start &
          sleep 10
          docker run --rm -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:3001 || true
